---
title: Project Review  
author: Kelly Hatfield
date: "`r file.mtime(knitr::current_input())`"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project:  COVID-19 Vaccination in Albany, GA

Name of project author(s): Jacob Matta

Name of project reviewer: Kelly Hatfield 


### Feedback and Comments
 The background and introduction are  thorough and provide good motiviation to the importance of the study. 

The abstract could use help with clarity, perhaps even a reframe the study some: 
The outcome of interest is the change in the proportion of residents vacccinated over time from September - February. The predictor of interest is the COVID-19 vaccine hesitancy program intervention. It would be helpful also to help contextualize the three zip codes of interest. 

### Summary assessment (PICK ONE, DELETE THE OTHERS)
* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments

The hypothesis and questions can be more explicitly stated in the manuscript. For example, in the objectives section you mention data cleaning methods. The objective should be stated more succinctly : 

We aim to assess any trend in vaccine uptake among our targeted community during the time of health literacy programs (September - February 2022) 

Your hypothesis is a little unclear to me too. For example, you are looking for an increase in the number of Albany citizens who receive the vaccine in the time period. However, this is a value that can't decrease. So are you looking for an increase in the trend (interrupted tiem series), and increase in the daily rate among unvaccinated (where your denominator will change daily), an increase in the zip codes of interest versus other zip codes where targeted interventions weren't applied? The objective/hypothesis might need to be fleshed out a bit more. 


### Summary assessment
* question/hypotheses somewhat explained


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The data structure is well explained and sources described. However, the author presents the findings as percents but states that the data source provides counts. He does not provide details on where the denominators for calculating percents come from. I see some population data in the processed dataset so I would encourage the author to describe the sources of that data too.  


### Summary assessment
* source and overall structure of data somewhat explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

Data processing is explained. However, I would be curious as to some of the data points. For example, the authors describe a decrease in vaccination rates over time. First, I would note that the decreases are small (<1%). Second, it is unclear how the decreases could occur (i.e., once a resident is vaccinated, they can't unvaccinated themself). This could be due to variation in the data or other factors, but should be addressed. 

The author also does the analyses over time in separate figures for each zip code. It would be helpful to have these on the same graph, perhaps grouped by color for if they are an intervention zip code or control zip code.  


### Summary assessment

* some weaknesses in wrangling and exploratory component




## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments
 
 There is limited analysis description in the manuscript. Per the analysis code file it appears there is detailed analysis with cross-fold validation. However, this is not described in the text. 

### Summary assessment
* wrong/inadequate analysis



## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments
The line graphs showing trends over time in the different zip codes are helpful. However, they could be improved with some additioanl work on the visualizations. In the manuscript the results for the advanced analysis are limited and not well described. 

### Summary assessment
* results are poorly presented, hard to understand, poor quality



## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments
Discussion not present at time of review. 

### Summary assessment

* major parts of discussion missing or wrong 


## Further comments


# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure


### Feedback and Comments
The project is well organized and the quarto files with code are well documented and easy to file. It is unclear to me if processingcode and processingcode2 quarto files need to reamin. I would update the readme section in that folder to make it clear which file does what part you are describing. 

### Summary assessment

* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments
The project is well documented. Some of the rationale for some of the caclulations is missing in some of the analysis files, but it is easy to understand the analytic parts. 

### Summary assessment

* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments
The analysis appears reproducible. However, some parts do appear to typed in (e.g., calculation of some rates) where it may be better to program the calculations to ensure typos don't affect your results. 

### Summary assessment

* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

The analysis seems thorough in the quarto files. However, from the manuscript file it is unclear. 

### Summary assessment


* decent level of thoroughness


## Further comments
This study could use a bit more thought and effort into the analysis and interpretation. I think the quarto files show a lot of really good exploratory analyses. The manuscript could use work to better describe the work and the findings. 

I don't think the references are formatted correctly, as they are also not populating in the manuscript. 
---
