---
title: "Processing Script 1"
author: "Jacob Matta"
date: "2023-01-03"
output: html_document
---

# Processing script 1


Load needed packages. make sure they are installed.

```{r}
library(here)
library(readxl) #for loading Excel files
library(dplyr) #for data processing/cleaning
library(tidyr) #for data processing/cleaning
```

### Raw Data & Codebook loading

```{r}
# Loading the rawdata containing GA residents with at least one dose of the Covid-19 vaccine
rawdata_location = here("data","raw_data","Sept_17.xlsx")
Sept_17 <- read_excel(rawdata_location)


#loading data code book for reference 
codebook_location = here("data","raw_data","Codebook.xlsx")
codebook = read_excel(codebook_location)
```

### Summary of data

```{r}
glimpse(Sept_17)
summary(Sept_17)
```

### Cleaning

```{r}
#I am only interested in Covid-19 Vaccination from Dougherty County which contains the target zip codes of 31701, 31705 and 31707
#by using filter() I am able to create a new dataset with vaccinations from Dougherty County 
Dougherty_Vax_Week1 <- filter(Sept_17, COUNTY_NAME == "Dougherty County")  

#replacing negative values with 0
Dougherty_Vax_Week1 [Dougherty_Vax_Week1 < 0] <- 0  
```
