---
title: "Manuscript for MADA Project"
subtitle: ""
author: Jacob Matta
date: "`r Sys.Date()`"
format:
  docx:
    toc: false
    number-sections: true
    highlight-style: github
bibliography: ../My_Library.bib
csl: ../apa.csl
---

# Summary

Back in March 2020, COVID-19 began to disproportionately impact the citizens of the United States. Among African Americans sub-population in rural South Georgia, there was a call to increase access to health services, promote health literacy as it relates to COVID-19 and decrease vaccine hesitancy. One such program includes the partnership between the City of Albany, GA and Albany State University to reduce COVID-19 vaccine hesitancy in Albany through a $3.9 million grant from Health and Human Services and the Office of Minority Health.

This study aims to conduct a secondary analysis of residents in Albany, GA that have received at least one dose of the COVID-19 vaccine and live in the one of the three zip codes 31701, 31705 and 31707.

{{< pagebreak >}}

# Introduction

## General Background

## Description of data and data source

The data is a count of residents with at least one COVID-19 vaccination by demographic in the state of Georgia released by the Georgia Department of Public Health. The data has 1962 observations which are 1962 different census tracts in Georgia. There are 187 variables each are a different combination of gender, race and age. The data is uploaded weekly.

The data is downloaded from the Georgia Department of Public Health Distribution Dashboard ([citation for dashboard pasted here](https://experience.arcgis.com/experience/3d8eea39f5c1443db1743a4cb8948a9c)) which is a publicly available dashboard that displays the current vaccination administered and the up-to-date count of Georgia residents that have been vaccinated. 

The data of interest from this dashboard is the data containing the count of residents with at least one dose of the COVID-19 vaccine by census tract by demographics. You can download the data from [the census tract demographic data](https://www.arcgis.com/home/item.html?id=17a8a4af79e5453a9132aaa29fb4ad22) and a description of the data by census tract demographic can be found on the separate dashboard found [here](https://insights.arcgis.com/#/view/08d2c1f995524053b1f9669dd0b0b995). 

## Objective

I am seeking to establish an efficient method of processing and cleaning the data to produce a data set with the target zip codes.

My goal is to compare monthly trends of vaccinations and examine whether there is an increase in vaccinations among African American residents during the time of the health literacy program, which is from September through April.

In other words, I am looking to see if the COVID-19 vaccine hesitancy program will have any observable effects through secondary data.

## Hypothesis

The city of Albany's population is predominately African American and by examining vaccination rates of African American residents in Albany, there will be an observable change in vaccinations over the course of the COVID-19 vaccine hesitancy program.

# Methods

## Data Import

After downloading the data the excel file containing the vaccination counts by census tract was saved to the rawdata file within this product and uploaded to a processing file where the intent is to clean and prepare the data for analysis. 

## Data Processing

In preparation for analysis, the raw data was first sub-setted by  Dougherty County, the county in which Albany, Georgia lies. This allowed me to work only with census tracts from Dougherty county. I then summed the data by demographic to get demographic totals 

# Results

# References

# Discussion
