# Overview

This file describes all files in this project, the reproducibility procedure for this project, any addition information regarding the methods, results and discussion for this project.

# Description of Project Files

-   `gitignore` file: Tells Git which files and directories to ignore when you make a commit

-   `JM-MADA-Project.Rproj` file: Establishes file paths for project

-   `data` folder: Contains the `processed_data` and `raw_data` folders

    -   `processed_data` folder: Contains the data that has been processed by the processing code

        -   `Zip_31701` folder: Contains processed data for the 31701 zip code

            -   `processed_data_31701_Sept.rds`: Contains processed data for the 31701 zip code during September, 2022

            -   `processed_data_31701_Oct.rds`: Contains processed data for the 31701 zip code during October, 2022

            -   `processed_data_31701_Nov.rds`: Contains processed data for the 31701 zip code during November, 2022

            -   `processed_data_31701_Dec.rds`: Contains processed data for the 31701 zip code during December, 2022

            -   `processed_data_31701_Jan.rds`: Contains processed data for the 31701 zip code during January, 2023

            -   `processed_data_31701_Feb.rds`: Contains processed data for the 31701 zip code during February, 2023

            -   `processed_combined_31701.rds`: Contains all vaccinations with all variables by month (September-February) for African Americans in the 31701 zip
           
            -   processed_POP_data_31701_Sept.rds`: Contains processed data for the 31701 zip code Total Black Population during September, 2022

            -   processed_POP_data_31701_Oct.rds`: Contains processed data for the 31701 zip code Total Black Population during October, 2022

            -   processed_POP_data_31701_Nov.rds`: Contains processed data for the 31701 zip code Total Black Population during November, 2022

            -   processed_POP_data_31701_Dec.rds`: Contains processed data for the 31701 zip code Total Black Population during December, 2022

            -   processed_POP_data_31701_Jan.rds`: Contains processed data for the 31701 zip code Total Black Population during January, 2023

            -   processed_POP_data_31701_Feb.rds`: Contains processed data for the 31701 zip code Total Black Population during February, 2023

            -   `processed_POP_combined_31701.rds`: Contains Total Population with all variables by month (September-February) for African Americans in the 31701 zip
            
        -   `Zip_31705` folder: Contains processed data for the 31705 zip code

            -   `processed_data_31705_Sept.rds`: Contains processed data for the 31705 zip code during September, 2022

            -   `processed_data_31705_Oct.rds`: Contains processed data for the 31705 zip code during October, 2022

            -   `processed_data_31705_Nov.rds`: Contains processed data for the 31705 zip code during November, 2022

            -   `processed_data_31705_Dec.rds`: Contains processed data for the 31705 zip code during December, 2022

            -   `processed_data_31705_Jan.rds`: Contains processed data for the 31705 zip code during January, 2022

            -   `processed_data_31705_Feb.rds`: Contains processed data for the 31705 zip code during Feb ruary, 2022
           
            -   processed_POP_data_31705_Sept.rds`: Contains processed data for the 31705 zip code Total Black Population during September, 2022

            -   processed_POP_data_31705_Oct.rds`: Contains processed data for the 31705 zip code Total Black Population during October, 2022

            -   processed_POP_data_31705_Nov.rds`: Contains processed data for the 31705 zip code Total Black Population during November, 2022

            -   processed_POP_data_31705_Dec.rds`: Contains processed data for the 31705 zip code Total Black Population during December, 2022

            -   processed_POP_data_31705_Jan.rds`: Contains processed data for the 31705 zip code Total Black Population during January, 2023

            -   processed_POP_data_31705_Feb.rds`: Contains processed data for the 31705 zip code Total Black Population during February, 2023

            -   `processed_POP_combined_31705.rds`: Contains Total Population with all variables by month (September-February) for African Americans in the 31705 zip
            
        -   `Zip_31707` folder: Contains processed data for the 31707 zip code

            -   `processed_data_31707_Sept.rds`: Contains processed data for the 31707 zip code during September, 2022

            -   `processed_data_31707_Oct.rds`: Contains processed data for the 31707 zip code during October, 2022

            -   `processed_data_31707_Nov.rds`: Contains processed data for the 31707 zip code during November, 2022

            -   `processed_data_31707_Dec.rds`: Contains processed data for the 31707 zip code during December, 2022

            -   `processed_data_31707_Jan.rds`: Contains processed data for the 31707 zip code during January, 2023

            -   `processed_data_31707_Feb.rds`: Contains processed data for the 31707 zip code during February, 2023
          
            -   processed_POP_data_31707_Sept.rds`: Contains processed data for the 31707 zip code Total Black Population during September, 2022

            -   processed_POP_data_31707_Oct.rds`: Contains processed data for the 31707 zip code Total Black Population during October, 2022

            -   processed_POP_data_31707_Nov.rds`: Contains processed data for the 31707 zip code Total Black Population during November, 2022

            -   processed_POP_data_31707_Dec.rds`: Contains processed data for the 31707 zip code Total Black Population during December, 2022

            -   processed_POP_data_31707_Jan.rds`: Contains processed data for the 31707 zip code Total Black Population during January, 2023

            -   processed_POP_data_31707_Feb.rds`: Contains processed data for the 31707 zip code Total Black Population during February, 2023

            -   `processed_POP_combined_31707.rds`: Contains Total Population with all variables by month (September-February) for African Americans in the 31707 zip

        -   `Zip_30815` folder: Contains processed data for the 31707 zip code
            -   `processed_data_30815_Sept.rds`: Contains processed data for the 30815 zip code during September, 2022

            -   `processed_data_30815_Oct.rds`: Contains processed data for the 30815 zip code during October, 2022

            -   `processed_data_30815_Nov.rds`: Contains processed data for the 30815 zip code during November, 2022

            -   `processed_data_30815_Dec.rds`: Contains processed data for the 30815 zip code during December, 2022

            -   `processed_data_30815_Jan.rds`: Contains processed data for the 30815 zip code during January, 2023

            -   `processed_data_30815_Feb.rds`: Contains processed data for the 30815 zip code during February, 2023
          
            -   processed_POP_data_30815_Sept.rds`: Contains processed data for the 30815 zip code Total Black Population during September, 2022

            -   processed_POP_data_30815_Oct.rds`: Contains processed data for the 30815 zip code Total Black Population during October, 2022

            -   processed_POP_data_30815_Nov.rds`: Contains processed data for the 30815 zip code Total Black Population during November, 2022

            -   processed_POP_data_30815_Dec.rds`: Contains processed data for the 30815 zip code Total Black Population during December, 2022

            -   processed_POP_data_30815_Jan.rds`: Contains processed data for the 30815 zip code Total Black Population during January, 2023

            -   processed_POP_data_30815_Feb.rds`: Contains processed data for the 30815 zip code Total Black Population during February, 2023 
       
        -   `Zip_30907` folder: Contains processed data for the 31707 zip code
          
            -   `processed_data_30907_Sept.rds`: Contains processed data for the 30907 zip code during September, 2022

            -   `processed_data_30907_Oct.rds`: Contains processed data for the 30907 zip code during October, 2022

            -   `processed_data_30907_Nov.rds`: Contains processed data for the 30907 zip code during November, 2022

            -   `processed_data_30907_Dec.rds`: Contains processed data for the 30907 zip code during December, 2022

            -   `processed_data_30907_Jan.rds`: Contains processed data for the 30907 zip code during January, 2023

            -   `processed_data_30907_Feb.rds`: Contains processed data for the 30907 zip code during February, 2023
            -   processed_POP_data_30907_Sept.rds`: Contains processed data for the 30907 zip code Total Black Population during September, 2022

            -   processed_POP_data_30907_Oct.rds`: Contains processed data for the 30907 zip code Total Black Population during October, 2022

            -   processed_POP_data_30907_Nov.rds`: Contains processed data for the 30907 zip code Total Black Population during November, 2022

            -   processed_POP_data_30907_Dec.rds`: Contains processed data for the 30907 zip code Total Black Population during December, 2022

            -   processed_POP_data_30907_Jan.rds`: Contains processed data for the 30907 zip code Total Black Population during January, 2023

            -   processed_POP_data_30907_Feb.rds`: Contains processed data for the 30907 zip code Total Black Population during February, 2023             
   
    -   `raw_data` folder: Contains the raw data for this project

        -   `Codebook.xlsx` : Contains the codebook for the raw data

        -   `Sept_17.xlsx`: Contains raw data that was downloaded on September 17th, 2022

        -   `Oct_28.xlsx`: Contains raw data that was downloaded on October 28th, 2022

        -   `Nov_24.xlsx`: Contains raw data that was downloaded on November 24th, 2022

        -   `Dec_29.xlsx`: Contains raw data that was downloaded on December 29th, 2022

        -   `Jan_26.xlsx`: Contains raw data that was downloaded on January 26th, 2023

        -   `Feb_26.xlsx`: Contains raw data that was downloaded on February 26th, 2023

-   `code` folder: Contains `analysis_code` folder and `processing_code` folder which are used to process the raw data into processed data through a series of cleaning steps and then using the analysis code to analyze the data

    -   `processing_code`: Contains the code for data processing in both .R files and .qmd files

        -   `processingcode.qmd`: processing code for COVID-19 vaccination data in the three target zip codes 31701, 31705 and 31707 and the two control zip codes 30815 and 30907
        
        -   `processingcode2.qmd`: processing code for COVID-19 Population data in the three target zip codes 31701, 31705 and 31707 and the two control zip codes 30815 and 30907
        
        -   `readme.md`: provides a brief description of the files in `processing_code` folder

    -   `analysis_code`: Contains the code for the analysis

        -   `exploratoryanalysis.qmd`: Contains the code to an analysis of the total amount of African Americans with at least one COVID-19 vaccine in all three target zip codes and two control zip codes
        
        -   `statisticalanalysis.qmd`: Contains the code to a statistical analysis of the total amount of African Americans with at least one COVID-19 vaccine in all three target zip codes and two control zip codes
        
        -   `readme.md`: provides a brief description of the analysis files

-   `products` folder: Contains files for the manuscript and supplementary material of this project

    -   `apa.csl` file: APA format for citations

    -   `Manuscript.qmd` file: Contains the manuscript for this project

    -   `My_Library.bib`: Bibliography for this project

    -   `readme.md`: Contains a description of the files in the `products` folder

    -   `supplement.qmd`: Contains supplementart material relevent to reproducing this project and a brief description of every file in this project

-   `results` folder: Contains the graphs produced from rendering the analysis 

    -   `31701_total_black_vax_rate.png` : A line graph of African Americans with at least one dose of the COVID-19 vaccine in the 31701 zip code
    
    -   `31705_total_black_vax_rate.png` : A line graph of African Americans with at least one dose of the COVID-19 vaccine in the 31705 zip code
    
    -   `31707_total_black_vax_rate.png`: A line graph of African Americans with at least one dose of the COVID-19 vaccine in the 31707 zip code
    
    -   `30815_total_black_vax_rate.png` : A line graph of African Americans with at least one dose of the COVID-19 vaccine in the 30815 zip code
    
    -   `30907_total_black_vax_rate.png` : A line graph of African Americans with at least one dose of the COVID-19 vaccine in the 30907 zip code
    
    -   `31701_Gender_black_vax.png`: A line graph of African Americans by Gender with at least one dose of the COVID-19 vaccine in the 31701 zip code
    
    -   `31705_Gender_black_vax.png`: A line graph of African Americans by Gender with at least one dose of the COVID-19 vaccine in the 31705 zip code
   
    -   `31707_Gender_black_vax.png`: A line graph of African Americans by Gender with at least one dose of the COVID-19 vaccine in the 31707 zip code
    
    -   `30815_Gender_black_vax.png`: A line graph of African Americans by Gender with at least one dose of the COVID-19 vaccine in the 30815 zip code
  
    -   `30907_Gender_black_vax.png`: A line graph of African Americans by Gender with at least one dose of the COVID-19 vaccine in the 30907 zip code   
    
    -   `31701_Age_black_vax.png`: A line graph of African Americans by Age with at least one dose of the COVID-19 vaccine in the 31701 zip code
    
    -   `31705_Age_black_vax.png`: A line graph of African Americans by Age with at least one dose of the COVID-19 vaccine in the 31705 zip code
   
    -   `31707_Age_black_vax.png`: A line graph of African Americans by Age with at least one dose of the COVID-19 vaccine in the 31707 zip code
    
    -   `30815_Age_black_vax.png`: A line graph of African Americans by Age with at least one dose of the COVID-19 vaccine in the 30815 zip code
  
    -   `30907_Age_black_vax.png`: A line graph of African Americans by Age with at least one dose of the COVID-19 vaccine in the 30907 zip code